"""add subscription fields to user

Revision ID: b86b7d3e675a
Revises: 04667dd365a0
Create Date: 2026-06-07 09:13:07.809247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86b7d3e675a'
down_revision: Union[str, Sequence[str], None] = '04667dd365a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', sa.String(length=16), nullable=False, server_default='free'))
    op.add_column('users', sa.Column('subscription_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_until')
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###
